###############################################################################################################################################

#Service File to deploy Face Rekognition application as Cluster IP service

apiVersion: v1
kind: Service
metadata:
  name: face-rekognition-service
  labels:
    app: face-rekognition
spec:
  selector:
    app: face-rekognition
  type: NodePort
  ports:
    - port: 80
      targetPort: 81
      protocol: TCP   